---
#cloud-config

# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

#
#
# This is far from anything like what is required at the moment.
# Just try testing with docker-compose for the moment. This is
# still blah.
#
#

users:
- name: tiddlywiki
  uid: 2000

write_files:
- path: /etc/systemd/system/tiddlywiki.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=TiddlyWiki 5 server

    [Service]
    ExecStart=/usr/bin/docker run --rm -u 2000 -v /home/tiddlywiki:/var/lib/tiddlywiki -p 8080:8080 --name=tiddlywiki nicolaw/tiddlywiki:latest
    ExecStop=/usr/bin/docker stop tiddlywiki
    ExecStopPost=/usr/bin/docker rm tiddlywiki

runcmd:
- systemctl daemon-reload
- systemctl start tiddlywiki.service
