#cloud-config

users:
- name: tiddlywiki
  uid: 2000
  homedir: /home/tiddlywiki

write_files:
- path: /etc/systemd/system/tiddlywiki-periodic-restart.timer
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Periodic TiddlyWiki restart

    [Timer]
    OnCalendar=weekly
    Persistent=true

    [Install]
    WantedBy=timers.target

- path: /etc/systemd/system/tiddlywiki-periodic-restart.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Periodic TiddlyWiki restart

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/systemctl try-restart tiddlywiki.service

- path: /etc/systemd/system/tiddlywiki.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=TiddlyWiki
    
    [Service]
    EnvironmentFile=/home/tiddlywiki/systemd/tiddlywiki.env
    WorkingDirectory=/home/tiddlywiki/docker
    ExecStart=/usr/bin/docker run --name=docker-compose \
                                  --rm --env-file env-file \
                                  -v /var/run/docker.sock:/var/run/docker.sock \
                                  -v "/home/tiddlywiki/docker:/rootfs/home/tiddlywiki/docker" \
                                  -w "/rootfs/home/tiddlywiki/docker" \
                                  docker/compose:1.19.0 \
                                  up --build --force-recreate
    ExecStop=/usr/bin/docker run  --name=docker-compose \
                                  --rm --env-file env-file \
                                  -v /var/run/docker.sock:/var/run/docker.sock \
                                  -v "/home/tiddlywiki/docker:/rootfs/home/tiddlywiki/docker" \
                                  -w "/rootfs/home/tiddlywiki/docker" \
                                  docker/compose:1.19.0 \
                                  down
    ExecStopPost=/usr/bin/docker stop docker-compose
    RestartSec=15
    Restart=always

runcmd:
- mkdir /home/tiddlywiki/systemd
- mkdir /home/tiddlywiki/letsencrypt
- mkdir /home/tiddlywiki/docker
- mkdir /home/tiddlywiki/docker/apache
- mkdir /home/tiddlywiki/docker/automation
- mkdir /home/tiddlywiki/docker/letsencrypt
- mkdir /home/tiddlywiki/docker/tiddlywiki
- chown -R tiddlywiki /home/tiddlywiki
- chgrp -R tiddlywiki /home/tiddlywiki
- systemctl daemon-reload
- systemctl start tiddlywiki.service || true
- systemctl enable tiddlywiki-periodic-restart.service || true
- systemctl start tiddlywiki-periodic-restart.service || true
