---
# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

# https://docs.docker.com/compose/compose-file

version: "3.4"

volumes:
  htdocs:
  tiddlywiki:
  # BUG: https://github.com/moby/moby/issues/3465
  #letsencrypt:

services:
  automation:
    build:
      context: automation
    environment:
      EMAIL: "${EMAIL:-webmaster@localhost.localdomain}"
      DOMAIN: "${DOMAIN:-localhost.localdomain}"
      GIT_REPOSITORY: "$GIT_REPOSITORY"
      GIT_USERNAME: "$GIT_USERNAME"
      GIT_PASSWORD: "$GIT_PASSWORD"
    volumes:
      - source: tiddlywiki
        target: /var/lib/tiddlywiki/mywiki
        type: volume
      - source: htdocs
        target: /var/lib/tiddlywiki/htdocs
        type: volume
      - source: "${LETSENCRYPT_DATA:-/etc/letsencrypt}"
        target: /var/lib/tiddlywiki/letsencrypt
        # BUG: https://github.com/moby/moby/issues/3465
        type: bind

  letsencrypt:
    build:
      context: letsencrypt
    environment:
      EMAIL: "${EMAIL:-webmaster@localhost.localdomain}"
      DOMAIN: "${DOMAIN:-localhost.localdomain}"
    depends_on:
      - automation
    volumes:
      - source: htdocs
        target: /usr/local/apache2/htdocs
        type: volume
      - source: "${LETSENCRYPT_DATA:-/etc/letsencrypt}"
        target: /etc/letsencrypt
        # BUG: https://github.com/moby/moby/issues/3465
        type: bind
    healthcheck:
      # TODO: Use openssl and/or certbot to validate the certificates and expiry dates.
      test: ["CMD", "ls", "/etc/letsencrypt/live/$DOMAIN/cert.pem"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 10s

  tiddlywiki:
    build:
      context: tiddlywiki
    environment:
      TW_USERNAME: "${TW_USERNAME:-anonymous}"
    expose:
      - 8080
    depends_on:
      - automation
    volumes:
      - source: tiddlywiki
        target: /var/lib/tiddlywiki/mywiki
        type: volume
    healthcheck:
      # TODO: Improve this to retrieve a known core system tiddler perhaps?
      test: ["CMD-SHELL", "printf 'GET /status HTTP/1.0\r\nHost: dinglebop.com\r\n\r\n' | nc localhost 8080 | grep -wq tiddlywiki_version"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 10s

  apache:
    build:
      context: apache
    environment:
      EMAIL: "${EMAIL:-webmaster@localhost.localdomain}"
      DOMAIN: "${DOMAIN:-localhost.localdomain}"
      TW_USERNAME: "${TW_USERNAME:-anonymous}"
      TW_PASSWORD: "${TW_PASSWORD:-password}"
      TW_PRIVATE: "${TW_PRIVATE:-}"
    depends_on:
      - tiddlywiki
      - letsencrypt
    links:
      - tiddlywiki:8080
    ports:
      - 80:80
      - 443:443
      - 444:444
    volumes:
      - source: htdocs
        target: /usr/local/apache2/htdocs
        type: volume
        read_only: true
      - source: "${LETSENCRYPT_DATA:-/etc/letsencrypt}"
        target: /etc/letsencrypt
        # BUG: https://github.com/moby/moby/issues/3465
        type: bind
        read_only: true
    healthcheck:
      # TODO: Improve to test operation modes of all three tcp/80,443,444 ports.
      test: ["CMD-SHELL", "printf 'HEAD / HTTP/1.1\r\nHost: dinglebop.com\r\n\r\n' | nc localhost 80 | grep -wqF 'Location: https://dinglebop.com/'"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 10s
