---
# MIT License
# Copyright (c) 2018 Nicola Worthington <nicolaw@tfb.net>

# https://docs.docker.com/compose/compose-file

version: "3.4"

volumes:
  htdocs:
  tiddlywiki:
  # BUG: https://github.com/moby/moby/issues/3465
  #letsencrypt:

services:
  automation:
    build:
      context: automation
    environment:
      EMAIL: "${EMAIL:-webmaster@localhost.localdomain}"
      DOMAIN: "${DOMAIN:-localhost.localdomain}"
    depends_on:
      - tiddlywiki
    volumes:
      - source: tiddlywiki
        target: /var/lib/tiddlywiki
        type: volume
      - source: htdocs
        target: /var/lib/tiddlywiki/htdocs
        type: volume
      - source: /tmp/tiddlywiki-letsencrypt
        target: /etc/letsencrypt
        # BUG: https://github.com/moby/moby/issues/3465
        type: bind
        read_only: true

  letsencrypt:
    build:
      context: letsencrypt
    environment:
      EMAIL: "${EMAIL:-webmaster@localhost.localdomain}"
      DOMAIN: "${DOMAIN:-localhost.localdomain}"
    volumes:
      - source: htdocs
        target: /usr/local/apache2/htdocs
        type: volume
      - source: /tmp/tiddlywiki-letsencrypt
        target: /etc/letsencrypt
        # BUG: https://github.com/moby/moby/issues/3465
        type: bind
    healthcheck:
      # TODO: Use openssl and/or certbot to validate the certificates and expiry dates.
      test: ["CMD", "ls", "-l", "/etc/letsencrypt/live/*/*.pem"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 10s

  tiddlywiki:
    build:
      context: tiddlywiki
    environment:
      TW_PORT: "${TW_PORT:-8080}"
      TW_ROOTTIDDLER: "${TW_ROOTTIDDLER:-$:/core/save/all}"
      TW_RENDERTYPE: "${TW_RENDERTYPE:-text/plain}"
      TW_SERVETYPE: "${TW_SERVERTYPE:-text/html}"
      TW_USERNAME: "${TW_USERNAME:-anonymous}"
      # We use Apache to overlay basic authentication on port tcp/444 only.
      #TW_PASSWORD: "${TW_PASSWORD:-}"
      TW_HOST: "${TW_HOST:-}"
      TW_PATHPREFIX: "${TW_PATHPREFIX:-}"
    expose:
      - 8080
    volumes:
      - source: tiddlywiki
        target: /var/lib/tiddlywiki
        type: volume
    healthcheck:
      # TODO: Improve this to retrieve a known core system tiddler perhaps?
      test: ["CMD-SHELL", "printf 'GET /status HTTP/1.0\r\nHost: dinglebop.com\r\n\r\n' | nc localhost 8080 | grep -wq tiddlywiki_version"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 10s

  apache:
    build:
      context: apache
    environment:
      EMAIL: "${EMAIL:-webmaster@localhost.localdomain}"
      DOMAIN: "${DOMAIN:-localhost.localdomain}"
      TW_USERNAME: "${TW_USERNAME:-$USER}"
      TW_PASSWORD: "${TW_PASSWORD:-password}"
    depends_on:
      - tiddlywiki
      - letsencrypt
    links:
      - tiddlywiki:8080
    ports:
      - 80:80
      - 443:443
      - 444:444
    volumes:
      - source: htdocs
        target: /usr/local/apache2/htdocs
        type: volume
        read_only: true
      - source: /tmp/tiddlywiki-letsencrypt
        target: /etc/letsencrypt
        # BUG: https://github.com/moby/moby/issues/3465
        type: bind
        read_only: true
    healthcheck:
      # TODO: Improve to test operation modes of all three tcp/80,443,444 ports.
      test: ["CMD-SHELL", "printf 'HEAD / HTTP/1.1\r\nHost: dinglebop.com\r\n\r\n' | nc localhost 80 | grep -wqF 'Location: https://dinglebop.codm/'"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 10s
